version: "3.3"

services:
    node_applications:
        container_name: node-applications
        build:
            context: ./node-applications
            dockerfile: Dockerfile
        environment:
            DNSCHANGER_CRON_INTERVAL: '* * * * *'
            DNSCHANGER_CLOUDFLARE_USERNAME: xxx
            DNSCHANGER_CLOUDFLARE_KEY: xxx
            DNSCHANGER_CLOUDFLARE_SEARCH_NAME: xxx
            DNSCHANGER_CLOUDFLARE_ZONE_ID: xxx
        restart: always
    verdaccio:
        container_name: verdaccio
        image: verdaccio/verdaccio:4
        ports:
            - "4873:4873"
        restart: always
        volumes:
            - verdaccio:/verdaccio

    # nginx:
    #     container_name: nginx
    #     build:
    #         context: ""
    #         dockerfile: nginx-reverse-proxy/Dockerfile
    #     ports:
    #         - "80:80"
    #     depends_on:
    #         - verdaccio

    # https://hub.docker.com/r/dperson/samba
    samba:
        image: dperson/samba:latest
        container_name: samba-dperson
        restart: always
        volumes:
            - ./storage/samba/anonymous:/samba/anonymous
            - ./storage/samba/admin:/samba/admin
            # - ./samba/smb.conf:/etc/samba/smb.conf
        environment:
            GLOBAL1: 'access based share enum = yes'
            USER1: 'adminUser;admin'
            SHARE1: 'public;/samba/anonymous'
            SHARE2: 'admin;/samba/admin;yes;no;no;adminUser'
        ports:
            - "139:139"
            - "445:445"

volumes:
    verdaccio:
        driver: local
