version: "3.3"

services:
    node_applications:
        container_name: node-applications
        build:
            context: ./node-applications
            dockerfile: Dockerfile
        environment:
            DNSCHANGER_CRON_INTERVAL: '* * * * *'
            DNSCHANGER_CLOUDFLARE_USERNAME: xxx
            DNSCHANGER_CLOUDFLARE_KEY: xxx
            DNSCHANGER_CLOUDFLARE_SEARCH_NAME: xxx
            DNSCHANGER_CLOUDFLARE_ZONE_ID: xxx
        restart: always

    verdaccio:
        container_name: verdaccio
        image: verdaccio/verdaccio:4
        ports:
            - "4873:4873"
        restart: always
        volumes:
            - ./storage/verdaccio:/verdaccio

    # https://hub.docker.com/r/dperson/samba
    samba:
        image: dperson/samba:latest
        container_name: samba-dperson
        restart: always
        volumes:
            - ./storage/samba/admin:/samba/admin
            - ./storage/samba/anonymous:/samba/anonymous
            - ./samba/smb.conf:/etc/samba/smb.conf
        environment:
            USER: 'kube_k;admin'
            # PERMISSIONS: 'admin'
            # GLOBAL1: 'access based share enum = yes'
            # SHARE1: 'guest;/samba/anonymous;yes;no;no;'
            # SHARE2: 'admin2;/samba/admin;yes;no;no;kube_k'
        ports:
            - "139:139"
            - "445:445"

    # nginx:
    #     container_name: nginx
    #     build:
    #         context: ""
    #         dockerfile: nginx-reverse-proxy/Dockerfile
    #     ports:
    #         - "80:80"
    #     depends_on:
    #         - verdaccio

volumes:
    verdaccio:
        driver: local
